sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
 # - GHCVER=7.6.3  ESVER=1.6.0 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.0.3 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.1.2 # Deprecated
 - GHCVER=7.8  ESVER=1.2.4
 - GHCVER=7.8  ESVER=1.3.6
 - GHCVER=7.8  ESVER=1.4.1
 - GHCVER=7.10 ESVER=1.5.2
 - GHCVER=7.10 ESVER=1.6.0
 - GHCVER=7.10 ESVER=1.7.2

install:
  # stack
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar -xvzf -
  - mv stack ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - stack --version

script:
  - make setup build test

cache:
  directories:
  - $HOME/.stack
